# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: coverage

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  report-coverage-diff:
    if: ${{ github.event_name == 'pull_request' }}
    strategy:
      matrix:
        node-version: [ 14.x ]
        platform: [ ubuntu-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - uses: anuraag016/Jest-Coverage-Diff@master
        with:
          fullCoverageDiff: false

  upload-coverage-report:
    if: ${{ github.event_name == 'push' }}
    strategy:
      matrix:
        node-version: [ 14.x ]
        platform: [ ubuntu-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run test --coverage
      - run: ls -la
      - uses: codecov/codecov-action@v1
        with:
          file: ./coverage/lcov.info
          fail_ci_if_error: true
          verbose: true
