# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: coverage

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  coverage:
    strategy:
      matrix:
        node-version: [ 14.x ]
        platform: [ ubuntu-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: Report coverage diff
        if: ${{ github.event_name == 'pull_request' }}
        uses: anuraag016/Jest-Coverage-Diff@master
        with:
          fullCoverageDiff: false
          runCommand: jest --coverage --coverageReporters="json-summary" --coverageDirectory="./"
      - name: Upload coverage report
        if: ${{ github.event_name == 'push' }}
        run: bash <(curl -s https://codecov.io/bash)
